[[https://melpa.org/#/casual-suite][file:https://melpa.org/packages/casual-suite-badge.svg]] [[https://stable.melpa.org/#/casual-suite][file:https://stable.melpa.org/packages/casual-suite-badge.svg]]

* Casual Suite

Casual Suite is an umbrella package to support a single installation point for all Casual user interfaces for Emacs. This is accomplished by including child packages as dependencies via the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][Elisp library header]] ~Package-Requires~.

The organization of Casual Suite is as follows:

- Casual Suite — Umbrella package
  - [[https://github.com/kickingvegas/casual][Casual]] — Library of interfaces for built-in Emacs modes.
  - [[https://github.com/kickingvegas/casual-avy][Casual Avy]]  — Interface for Avy (3^{rd} party)
  - [[https://github.com/kickingvegas/casual-symbol-overlay][Casual Symbol Overlay]] — Interface for Symbol Overlay (3^{rd} party)
  
* Requirements

Casual Suite requires [[https://github.com/magit/transient][Transient]] 0.9+. Versions of GNU Emacs 30.1 or greater will satisfy this requirement with its built-in version of Transient.

The following 3^{rd} party packages are also required but will be installed as dependencies if not present.

- [[https://github.com/abo-abo/avy][Avy]] ≥ 0.5.0
- [[https://github.com/wolray/symbol-overlay][Symbol Overlay]] ≥ 4.2  

Casual Suite has been verified with the following configuration.

- GNU Emacs 31.1 (macOS 15.7, Ubuntu Linux 22.04.5 LTS)

* Install

Casual Suite versions 3.0 or greater offer a simplified installation with the command ~casual-suite-init~. By default this command will setup interfaces for all supported Casual modules, both built-in modes/modules and 3^{rd} party. Run this via ~execute-execute-command~ (~M-x~) or add the following Elisp to your Emacs initialization file.

#+begin_src elisp :lexical no
  (require 'casual-suite)
  (casual-suite-init)
#+end_src

Note that ~casual-suite-init~ will only work if Casual Suite is installed via ~package-install~.

If /à la carte/ style setup of Casual modules is desired, then confer with the install instructions provided by the following packages.

- [[https://kickingvegas.github.io/casual/Install.html][Casual Install]]
- [[https://kickingvegas.github.io/casual-avy/Install.html][Casual Avy Install]]
- [[https://kickingvegas.github.io/casual-symbol-overlay/Install.html][Casual Symbol Overlay Install]]
  
* Sponsorship

If you enjoy using Casual Suite, please consider buying me a coffee to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]
  
* Acknowledgments

A heartfelt thanks to all the contributors to the GNU Emacs ecosystem from which Casual Suite builds from. This work would not be possible without your efforts.
