* Casual Suite
An umbrella package to support a single installation point for all Casual porcelains. These porcelains are included via the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][Elisp library header]] ~Package-Requires~. Included porcelains are:

- [[https://github.com/kickingvegas/casual][Casual Calc]] - a Transient porcelain for Emacs Calc.
- [[https://github.com/kickingvegas/casual-dired][Casual Dired]] - a Transient porcelain for the Emacs file manager Dired.
- [[https://github.com/kickingvegas/casual-avy][Casual Avy]] - a Transient porcelain for Avy.
- [[https://github.com/kickingvegas/casual-info][Casual Info]] - a Transient porcelain for Info.  
- [[https://github.com/kickingvegas/cc-isearch-menu][cc-isearch-menu]] - a Transient menu for I-Search.

* Requirements
Casual Suite has been verified with the following configuration. 
- Emacs 29.3 (macOS 14.5, Ubuntu Linux 22.04.4 LTS)

* Asks
As Casual Suite is new, we are looking for early adopters! Your [[https://github.com/kickingvegas/casual-info/discussions][feedback]] is welcome as it will likely impact Casual Suite's evolution, particularly with regards to UI.

* Install
It is highly recommended that a deep reading of the install procedure for each porcelain be done beforehand as each of them have their own recommended customizations to go alongside them. Such customizations ensure that you have the best experience with each porcelain.

- [[https://github.com/kickingvegas/casual?tab=readme-ov-file#install][Casual Calc]]
- [[https://github.com/kickingvegas/casual-dired?tab=readme-ov-file#install][Casual Dired]] 
- [[https://github.com/kickingvegas/casual-avy?tab=readme-ov-file#install][Casual Avy]] 
- [[https://github.com/kickingvegas/casual-info?tab=readme-ov-file#install][Casual Info]] 
- [[https://github.com/kickingvegas/cc-isearch-menu?tab=readme-ov-file#install][cc-isearch-menu]]

** TL;DR
Impatient readers can use the following code to put into their Emacs initialization file to immediately use Casual Suite. 

The following lines illustrate an installation of the Casual Suite with no customization. 

#+begin_src elisp :lexical no
  (require 'casual-suite)
  (define-key calc-mode-map (kbd "C-o") #'casual-calc-tmenu)
  (define-key dired-mode-map (kbd "C-o") #'casual-dired-tmenu)
  (define-key info-mode-map (kbd "C-o") #'casual-info-tmenu)
  (keymap-global-set "M-g" #'casual-avy-tmenu)
  (define-key isearch-mode-map (kbd "<f2>") #'cc-isearch-menu-transient)
#+end_src

For an alternate install using ~use-package~:

#+begin_src elisp :lexical no
  (require 'casual-suite)
  (use-package casual
    :ensure t
    :bind (:map calc-mode-map ("C-o" . 'casual-calc-tmenu)))

  (use-package casual-info
    :ensure t
    :bind (:map Info-mode-map ("C-o" . 'casual-info-tmenu)))

  (use-package casual-dired
    :ensure t
    :bind (:map dired-mode-map ("C-o" . 'casual-dired-tmenu)))

  (use-package casual-avy
    :ensure t
    :bind ("M-g" . casual-avy-tmenu))

  (use-package cc-isearch-menu
    :ensure t
    :bind (:map isearch-mode-map ("<f2>" . 'cc-isearch-menu-transient)))
#+end_src

* Sponsorship
If you enjoy using Casual Suite, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]
  
* Acknowledgments
A heartfelt thanks to all the contributors to Calc, Dired, Info, I-Search, Info, and Transit. Casual Suite would not be possible without your efforts.

