[[https://melpa.org/#/casual-suite][file:https://melpa.org/packages/casual-suite-badge.svg]]

* Casual Suite
An umbrella package to support a single installation point for all Casual user interfaces for Emacs. These user interfaces built with [[https://github.com/magit/transient][Transient]] are included via the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][Elisp library header]] ~Package-Requires~. Included user interfaces are:

- [[https://github.com/kickingvegas/casual-isearch][Casual I-Search]] - a Transient menu for I-Search.
- [[https://github.com/kickingvegas/casual-dired][Casual Dired]] - a Transient user interface for the Dired file manager.
- [[https://github.com/kickingvegas/casual-info][Casual Info]] - a Transient user interface for Info.  
- [[https://github.com/kickingvegas/casual-calc][Casual Calc]] - a Transient user interface for Calc.
- [[https://github.com/kickingvegas/casual-ibuffer][Casual IBuffer]] - a Transient user interface for IBuffer.
- [[https://github.com/kickingvegas/casual-re-builder][Casual RE-Builder]] - a Transient user interface for RE-Builder.
- [[https://github.com/kickingvegas/casual-bookmarks][Casual Bookmarks]] - a Transient user interface for the bookmark list.
- [[https://github.com/kickingvegas/casual-agenda][Casual Agenda]] - a Transient user interface for Org Agenda.
- [[https://github.com/kickingvegas/casual-avy][Casual Avy]] - a Transient user interface for Avy.

* Requirements
Casual Suite has been verified with the following configuration. 
- Emacs 29.4 (macOS 14.5, Ubuntu Linux 22.04.4 LTS)

* Asks
As Casual Suite is new, we are looking for early adopters! Your [[https://github.com/kickingvegas/casual-info/discussions][feedback]] is welcome as it will likely impact Casual Suite's evolution, particularly with regards to UI.

* Install
It is highly recommended that a deep reading of the install procedure for each user interface be done beforehand as each of them have their own recommended customizations to go alongside them. Such customizations ensure that you have the best experience with each user interface.

- [[https://github.com/kickingvegas/casual-isearch?tab=readme-ov-file#install][Casual I-Search]]
- [[https://github.com/kickingvegas/casual-dired?tab=readme-ov-file#install][Casual Dired]] 
- [[https://github.com/kickingvegas/casual-info?tab=readme-ov-file#install][Casual Info]] 
- [[https://github.com/kickingvegas/casual-calc?tab=readme-ov-file#install][Casual Calc]]
- [[https://github.com/kickingvegas/casual-ibuffer?tab=readme-ov-file#install][Casual IBuffer]]
- [[https://github.com/kickingvegas/casual-re-builder?tab=readme-ov-file#install][Casual RE-Builder]]
- [[https://github.com/kickingvegas/casual-bookmarks?tab=readme-ov-file#install][Casual Bookmarks]]
- [[https://github.com/kickingvegas/casual-agenda?tab=readme-ov-file#install][Casual Agenda]]
- [[https://github.com/kickingvegas/casual-avy?tab=readme-ov-file#install][Casual Avy]]

** TL;DR
Impatient readers can use the following code to put into their Emacs initialization file to immediately use Casual Suite. 

The following lines illustrate an installation of the Casual Suite with no customization. The key bindings shown below are suggested but can always be changed to preference.

#+begin_src elisp :lexical no
  (require 'casual-suite)
  (keymap-set calc-mode-map "C-o" #'casual-calc-tmenu)
  (keymap-set dired-mode-map "C-o" #'casual-dired-tmenu)
  (keymap-set isearch-mode-map "<f2>" #'cc-isearch-menu-transient)
  (keymap-set ibuffer-mode-map "C-o" #'casual-ibuffer-tmenu)
  (keymap-set ibuffer-mode-map "F" #'casual-ibuffer-filter-tmenu)
  (keymap-set ibuffer-mode-map "s" #'casual-ibuffer-sortby-tmenu)
  (keymap-set Info-mode-map "C-o" #'casual-info-tmenu)
  (keymap-set reb-mode-map "C-o" #'casual-re-builder-tmenu)
  (keymap-set reb-lisp-mode-map "C-o" #'casual-re-builder-tmenu)
  (keymap-set bookmark-bmenu-mode-map "C-o" #'casual-bookmarks-tmenu)
  (keymap-set org-agenda-mode-map "C-o" #'casual-agenda-tmenu)
  (keymap-global-set "M-g" #'casual-avy-tmenu)
#+end_src

For users who prefer ~use-package~, it is highly recommended that ~casual-suite~ be installed via ~package.el~ or some equivalent package manager and /not/ through ~use-package~. As ~casual-suite~ is an umbrella install package, installing it with ~:ensure t~ alongside individual configurations of the Casual user interfaces that also install using ~:ensure t~ can lead to undesired order-dependent behavior.

The following minimal configuration code using ~use-package~ for configuring each Casual user interface is shown below. It is provided as an example to quickly use Casual Suite. As mentioned before, it is recommended that a deep read of the install procedure for each user interface be used for guidance for configuration.

#+begin_src elisp :lexical no
  (use-package casual-calc
    :ensure nil
    :bind (:map calc-mode-map ("C-o" . casual-calc-tmenu)))

  (use-package casual-info
    :ensure nil
    :bind (:map Info-mode-map ("C-o" . casual-info-tmenu)))

  (use-package casual-dired
    :ensure nil
    :bind (:map dired-mode-map ("C-o" . casual-dired-tmenu)))

  (use-package casual-avy
    :ensure nil
    :bind ("M-g" . casual-avy-tmenu))

  (use-package casual-isearch
    :ensure nil
    :bind (:map isearch-mode-map ("<f2>" . casual-isearch-tmenu)))

  (use-package ibuffer
    :hook (ibuffer-mode . ibuffer-auto-mode)
    :defer t)
  (use-package casual-ibuffer
    :ensure nil
    :bind (:map
           ibuffer-mode-map
           ("C-o" . casual-ibuffer-tmenu)
           ("F" . casual-ibuffer-filter-tmenu)
           ("s" . casual-ibuffer-sortby-tmenu)
           ("<double-mouse-1>" . ibuffer-visit-buffer) ; optional
           ("M-<double-mouse-1>" . ibuffer-visit-buffer-other-window) ; optional
           ("{" . ibuffer-backwards-next-marked) ; optional
           ("}" . ibuffer-forward-next-marked)   ; optional
           ("[" . ibuffer-backward-filter-group) ; optional
           ("]" . ibuffer-forward-filter-group)  ; optional
           ("$" . ibuffer-toggle-filter-group))  ; optional
    :after (ibuffer))

  (use-package re-builder
    :defer t)
  (use-package casual-re-builder
    :ensure nil
    :bind (:map
           reb-mode-map ("C-o" . casual-re-builder-tmenu)
           :map
           reb-lisp-mode-map ("C-o" . casual-re-builder-tmenu))
    :after (re-builder))

  (use-package bookmark
    :ensure nil
    :defer t)
  (use-package casual-bookmarks
    :ensure nil
    :bind (:map bookmark-bmenu-mode-map
                ("C-o" . casual-bookmarks-tmenu)
                ("S" . casual-bookmarks-sortby-tmenu)
                ("J" . bookmark-jump))
    :after (bookmark))

  (use-package casual-agenda
    :ensure nil
    :bind (:map
           org-agenda-mode-map
           ("C-o" . casual-agenda-tmenu)
           ("M-j" . org-agenda-clock-goto) ; optional
           ("J" . bookmark-jump))) ; optional
#+end_src

* Sponsorship
If you enjoy using Casual Suite, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]
  
* Acknowledgments
A heartfelt thanks to all the contributors to Calc, Dired, Info, I-Search, Info, IBuffer, RE-Builder, Bookmarks, Avy, and [[https://github.com/magit/transient][Transient]]. Casual Suite would not be possible without your efforts.
